### ISSUE TITLE
Скорректировать вручную сгенерированные автоматом два класса

### ISSUE THREAD

**Issue by irbismaestro** [AndreyMenshikov/vetisapi#1]
Вот мне удалось погасить Вами сгенерированный сертифкат...
Но чтоб этого добится мне пришлось пойти на очень нестандратный шаг.,-Скорректировать вручную сгенерированные автоматом два класса
`Delivery и ConsignmentDocumentList`
Другого пути я не видел...Поправьте меня,пожалуйста , если я чего -то "не догнал".
1.Чтоб погасить сертификат надо пользовать класс
 ProcessIncomingConsignmentRequest
https://help.vetrf.ru/wiki/IncomingOperation_for_veterinary_control#.D0.9E.D0.B1.D1.8A.D0.B5.D0.BA.D1.82_..Request.2Fdelivery.2Fconsignment
тут вроде не мождет быть косяка.
2.Он требует на вход Delivery
А вот delivery требует
 List<Consignment> consignment
И вот блин ...нету в сгенерированном классе Delivery(В Вашем коде автоматическом тоже) метода
   ```
 public void setConsignment(List<Consignment> consignment) {
        this.consignment = consignment;
    }
```
Я добавляю этот код  сам.
3.При наполнении метода
```
setAccompanyingForms(ConsignmentDocumentList value)
класс ConsignmentDocumentList должен быть наполнен
List<VetDocument> vetCertificate
```
и вот опять метода (и У Вас тоже в автоматом сгенерированном)
  ```
  public void setVetCertificate(List<VetDocument> vetCertificate) {
        this.vetCertificate = vetCertificate;
    }
```

НЕТ...добавил сам...
И Сертификат погасился.

НО вот я посмотрел(сделал реверс инжениринг) некоторых мобильных apk по меркурию(Ваш тоже смотрел,но Вы работаете с сервис-кабинетом)
Так вот там эти классы не измененны...ну а глубоко копать(изучать из код) не хотелось...ведь я всё же уже результат получил...пусть и не совсем стандарнтно..но стандартного пути по этим классам просто нет.(Во всяком случае мне сейчас так кажется).

Вы можете как-то это прокомментировать?.

**Comment by AndreyMenshikov** [comment]
Да, там не все так очевидно :)

Метод set не нужен.

Delivery del = new Delivery();
...
Consignment cons = new Consignment();
...
del.getConsignment().add(cons);


список уже инициализируется при вызове get, вот часть кода класса Delivery

    public List<Consignment> getConsignment() {
        if (consignment == null) {
            consignment = new ArrayList<Consignment>();
        }
        return this.consignment;
    }


С другими списками аналогично.
